name = "wikipedia-mcp-server"
main = "dist/worker.js"
compatibility_date = "2024-11-01"

[build]
command = "npm run build"

# KV storage for persistent caching
[[kv_namespaces]]
binding = "WIKI_CACHE"
id = "your-kv-namespace-id"  # Replace with your actual KV namespace ID
preview_id = "your-preview-kv-namespace-id"  # Replace with your preview KV namespace ID

# Environment variables for configuration
[env.production.vars]
CACHE_MAX = "500"
CACHE_TTL = "600000"  # 10 minutes
DEFAULT_LANGUAGE = "en"
ENABLE_DEDUPLICATION = "true"
LOG_LEVEL = "info"
ENABLE_METRICS = "true"

[env.staging.vars]
CACHE_MAX = "200"
CACHE_TTL = "300000"  # 5 minutes
DEFAULT_LANGUAGE = "en"
ENABLE_DEDUPLICATION = "true"
LOG_LEVEL = "debug"
ENABLE_METRICS = "true"

# Development environment (uses .dev.vars file)
[env.development]
vars = { }  # Variables loaded from .dev.vars

# Rate limiting (optional)
# [[services]]
# binding = "RATE_LIMITER"
# service = "your-rate-limiter-worker" 